### ISSUE TITLE
Incorrect Redirection or exptected Behavious

### ISSUE THREAD

**Issue by knit-pay** [wp-pay-extensions/woocommerce#4]
Hello Team

I can see here that the code is redirecting to the success page even if its status is Open or default. For some payment gateways, it takes time for the status to get updated to complete/success. Is it fine to redirect customers to the success page even before we get a success message from the payment gateway? Is it an expected behavior or a bug?

https://github.com/wp-pay-extensions/woocommerce/blob/85e52cbecd956cd149f15160504bcdf5455ed774/src/Extension.php#L413-L418

**Comment by rvdsteege** [comment]
It is indeed the desired behaviour to redirect to the thank you page. Ootherwise, customers will be redirected to a page to pay for the order, even though they just did that (or in case of for example a bank transfer: are planning to do so).

However, in this case when the order is still pending ('waiting for payment'), a message gets added to the thank you page to inform the customer that the order will be processed once the payment has been received.

https://github.com/wp-pay-extensions/woocommerce/blob/develop/src/Extension.php#L355-L386

**Comment by knit-pay** [comment]
Thanks for the information.
