### ISSUE TITLE
Error while placing WooCommerce Order.

### ISSUE THREAD

**Issue by knit-pay** [wp-pay-extensions/woocommerce#8]
Hello Team

One of my clients got this error while placing WooCommerce order. Do you have any idea what could be the reason for the same?

`2021/08/17 13:53:33 [error] 32667#32667: *1214 FastCGI sent in stderr: "PHP message: shipping_phone was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Pronamic\WordPress\Pay\Extensions\WooCommerce\Gateway->process_payment, Pronamic\WordPress\Pay\Extensions\WooCommerce\WooCommerce::get_shipping_phone, Pronamic\WordPress\Pay\Extensions\WooCommerce\WooCommerce::get_order_property, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong.`

**Comment by rvdsteege** [comment]
Thanks for reporting, Gautam. Seems we were using a non-existing `shipping_phone` order property for the payment shipping address, which resulted in your error message.
